#!/usr/bin/env python3
"""One-time script to write 2026-03-24 content drafts."""
import pathlib

base = pathlib.Path("/home/abzu/mega-os/drafts/social")

# Twitter thread
twitter = [
    "---",
    "platform: Twitter/X",
    "type: thread",
    "date: 2026-03-24",
    "topic: MCP three primitives, Resources and Prompts are being ignored",
    "anchor: drafts/article-mcp-architecture.md",
    "status: drafted",
    "---",
    "",
    "## Tweet 1 (236 chars)",
    "MCP defines three primitives: Tools, Resources, and Prompts.",
    "",
    "95% of implementations use Tools. Almost nobody uses the other two.",
    "",
    "That explains most of the context consumption complaints.",
    "",
    "A thread on the protocol nobody actually read.",
    "",
    "## Tweet 2 (271 chars)",
    "Tools are model-controlled. The LLM decides when to invoke them. Every tool description loads into the context window at startup.",
    "",
    "This is what Perplexity benchmarked. This is what eats 143,000 of 200,000 tokens before any agent does useful work.",
    "",
    "Fair criticism. Wrong target.",
    "",
    "## Tweet 3 (278 chars)",
    "Resources are application-controlled. They expose files, schemas, and system state through URIs. The app decides when to load them, not the model.",
    "",
    "Instead of dumping everything into the prompt, you load specific context when it becomes relevant. Selective, not exhaustive.",
    "",
    "## Tweet 4 (265 chars)",
    "Prompts are user-controlled templates. Versioned, parameterized, updated centrally without changing client code.",
    "",
    "If you maintain the same system prompt across multiple agents and wish you could update it in one place, that is what Prompts solve. It is already in the spec.",
    "",
    "## Tweet 5 (274 chars)",
    "Then there is Sampling. Almost nobody uses it.",
    "",
    "The server requests LLM completions back through the host. The MCP server becomes an orchestrator. Recursive reasoning loops. Nested chains.",
    "",
    "The topology is not flat anymore. It has depth. And the ecosystem has not noticed.",
    "",
    "## Tweet 6 (260 chars)",
    "When people say MCP eats too many tokens, they are describing a system that loaded all its Tools and none of its Resources.",
    "",
    "The protocol supports selective, efficient context delivery. Most implementations just do not use it.",
    "",
    "The protocol is not the problem. The pattern is.",
    "",
    "## Tweet 7 (198 chars)",
    "I wrote 2,400 words on MCP actual architecture, including the trust model gaps, the gateway tier emerging, and why Perplexity left.",
    "",
    "Publishes tomorrow on The Alignment Layer.",
    "",
    "[Substack link]",
]
(base / "2026-03-24-twitter.md").write_text("\n".join(twitter) + "\n")
print("Twitter saved")

# TikTok script
tiktok = [
    "---",
    "platform: TikTok",
    "type: video script",
    "date: 2026-03-24",
    "topic: Sampling, your MCP server can think",
    "anchor: drafts/article-mcp-architecture.md",
    "status: drafted",
    "duration_estimate: 50 seconds",
    "caption: MCP has a capability almost nobody uses. Your server can think.",
    "tags: mcp, aiagents, programming, buildinpublic, aidev",
    "visual_notes: Screen recording of MCP architecture diagram. Flat hub-and-spoke then animate recursive arrows. Face cam for hook and closing.",
    "---",
    "",
    "**[HOOK, 0-3s]**",
    "Your MCP server can call the AI back.",
    "",
    "**[PROBLEM, 3-15s]**",
    "Everyone uses MCP the same way. The model calls a tool, the tool returns data, done. Flat. One direction.",
    "",
    "But the protocol has a capability called Sampling that almost nobody touches. And it changes the entire architecture.",
    "",
    "**[INSIGHT, 15-40s]**",
    "Sampling lets the MCP server request LLM completions back through the host. The server becomes a client of the model. The model calls the server, the server calls back to the model, the model calls another server.",
    "",
    "You get recursive orchestration. Nested reasoning chains. Your MCP server is not just a tool anymore. It is a thinker.",
    "",
    "Most people building MCP today are building flat spokes. The protocol already supports depth. The gap between what is deployed and what is possible is enormous.",
    "",
    "**[CTA, 40-50s]**",
    "I wrote a deep dive on the MCP primitives nobody uses. Link in bio. Follow if you are building with agents.",
    "",
    "---",
    "",
    "**Duration:** ~50 seconds",
    "**Caption:** MCP has a capability almost nobody uses. Your server can think.",
]
(base / "2026-03-24-tiktok.md").write_text("\n".join(tiktok) + "\n")
print("TikTok saved")

# LinkedIn post
linkedin = [
    "---",
    "platform: LinkedIn",
    "type: insight post",
    "date: 2026-03-24",
    "topic: MCP is context delivery not orchestration, category confusion explains the backlash",
    "anchor: drafts/article-mcp-architecture.md",
    "status: drafted",
    "word_count: ~230",
    "---",
    "",
    "Perplexity's CTO announced they are moving away from MCP. Context consumption was killing them. One deployment showed three MCP servers eating 143,000 of 200,000 tokens before any agent did useful work.",
    "",
    "The criticism is fair. But the conclusion most people drew from it misses something.",
    "",
    "MCP is a context delivery protocol. It moves structured data between models and tools. That is its job. It was not designed to be an orchestration framework.",
    "",
    "When teams load every tool description at startup, connect everything, and run out of room to think, the problem is not the protocol. It is the architecture. They built an orchestration layer on top of a delivery layer and wondered why it collapsed under weight.",
    "",
    "MCP handles context delivery. A2A handles agent coordination. Workflow engines handle sequencing and error recovery. Each one has a job. Expecting any single protocol to do all three produces exactly the bloated deployments that got criticized.",
    "",
    "The teams getting this right treat MCP as a thin translation layer. Business logic stays in the services behind it. Context loads selectively, not exhaustively. Trust boundaries are enforced at the gateway, not assumed at the host.",
    "",
    "The protocol won the standardization battle (tens of millions of monthly SDK downloads, Linux Foundation donation). But winning standardization and winning architecture are different things.",
    "",
    "What is the biggest architectural mistake you have seen teams make when adopting a new protocol standard?",
]
(base / "2026-03-24-linkedin.md").write_text("\n".join(linkedin) + "\n")
print("LinkedIn saved")
